Assignment-2 #part (b)

Working with the 2010 Q1 dataset break apart the performance data to a training and validation set where the training set is everything before 2015 and the validation set is everything after

In [83]:
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt

In [84]:
performance_df=pd.read_csv("C:/Users/krish/Desktop/Preety/Performance_2010Q1.txt" , sep="|")

C:\Users\krish\Anaconda\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (14,15,16) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [85]:
#print(performance_df)

In order to know the number of columns in the dataset

In [86]:
performance_df.shape

(999999, 31)

In [87]:
Columns = {0: "loan_id", 1: "DATE", 15: "forclosure_date"}
col_names = [Columns.get(idx, "%d"% idx) for idx, _ in enumerate(range(31))]
performance_df = pd.read_csv("C:/Users/krish/Desktop/Preety/Performance_2010Q1.txt",header=None,names=col_names,sep="|")

C:\Users\krish\Anaconda\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (14,15,16) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [88]:
split = performance_df['DATE'].map(lambda x: int(x[-4:])<2015)

In [89]:
train = performance_df[split]
test = performance_df[~split]

Display the training set which is everything before 2015

In [90]:
train

,loan_id,DATE,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
0,100010079393,02/01/2010,"WELLS FARGO BANK, N.A.",4.875,NaN,0,360,360.0,02/2040,12420,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
1,100010079393,03/01/2010,NaN,4.875,NaN,1,359,358.0,02/2040,12420,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
2,100010079393,04/01/2010,NaN,4.875,NaN,2,358,358.0,02/2040,12420,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
3,100010079393,05/01/2010,NaN,4.875,NaN,3,357,357.0,02/2040,12420,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
4,100010079393,06/01/2010,NaN,4.875,NaN,4,356,355.0,02/2040,12420,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
5,100010079393,07/01/2010,NaN,4.875,NaN,5,355,354.0,02/2040,12420,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
6,100010079393,08/01/2010,NaN,4.875,281525.61,6,354,353.0,02/2040,12420,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
7,100010079393,09/01/2010,NaN,4.875,281166.36,7,353,352.0,02/2040,12420,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
8,100010079393,10/01/2010,NaN,4.875,280805.65,8,352,351.0,02/2040,12420,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
9,100010079393,11/01/2010,NaN,4.875,280443.47,9,351,350.0,02/2040,12420,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
10,100010079393,12/01/2010,NaN,4.875,280443.47,10,350,350.0,02/2040,12420,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
11,100010079393,01/01/2011,NaN,4.875,280443.47,11,349,0.0,02/2040,12420,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN
12,100013622306,01/01/2010,"JP MORGAN CHASE BANK, NA",4.750,NaN,0,180,179.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
13,100013622306,02/01/2010,NaN,4.750,NaN,1,179,178.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
14,100013622306,03/01/2010,NaN,4.750,NaN,2,178,177.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
15,100013622306,04/01/2010,NaN,4.750,NaN,3,177,177.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
16,100013622306,05/01/2010,NaN,4.750,NaN,4,176,175.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
17,100013622306,06/01/2010,NaN,4.750,NaN,5,175,174.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
18,100013622306,07/01/2010,NaN,4.750,84645.77,6,174,173.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
19,100013622306,08/01/2010,NaN,4.750,84304.11,7,173,172.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
20,100013622306,09/01/2010,NaN,4.750,83961.09,8,172,171.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
21,100013622306,10/01/2010,NaN,4.750,83616.72,9,171,170.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
22,100013622306,11/01/2010,NaN,4.750,83270.98,10,170,169.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
23,100013622306,12/01/2010,NaN,4.750,82923.87,11,169,168.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
24,100013622306,01/01/2011,NaN,4.750,82575.39,12,168,167.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
25,100013622306,02/01/2011,NaN,4.750,82225.53,13,167,166.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
26,100013622306,03/01/2011,NaN,4.750,81874.29,14,166,165.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
27,100013622306,04/01/2011,NaN,4.750,81521.66,15,165,164.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
28,100013622306,05/01/2011,NaN,4.750,81167.63,16,164,163.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
29,100013622306,06/01/2011,NaN,4.750,80812.20,17,163,162.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999970,149180644668,05/01/2010,NaN,4.875,NaN,3,357,355.0,02/2040,17780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
999971,149180644668,06/01/2010,NaN,4.875,NaN,4,356,354.0,02/2040,17780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
999972,149180644668,07/01/2010,NaN,4.875,NaN,5,355,353.0,02/2040,17780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
999973,149180644668,08/01/2010,NaN,4.875,116119.23,6,354,352.0,02/2040,17780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
999974,149180644668,09/01/2010,NaN,4.875,115969.66,7,353,351.0,02/2040,17780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
999975,149180644668,10/01/2010,NaN,4.875,115819.49,8,352,350.0,02/2040,17780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
999976,149180644668,11/01/2010,NaN,4.875,115668.71,9,351,349.0,02/2040,17780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
999977,149180644668,12/01/2010,NaN,4.875,115365.30,10,350,347.0,02/2040,17780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
999978,149180644668,01/01/2011,NaN,4.875,115365.30,11,349,347.0,02/2040,17780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
999979,149180644668,02/01/2011,NaN,4.875,115212.67,12,348,346.0,02/2040,17780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
999980,149180644668,03/01/2011,NaN,4.875,115059.42,13,347,345.0,02/2040,17780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
999981,149180644668,04/01/2011,NaN,4.875,114750.79,14,346,343.0,02/2040,17780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
999982,149180644668,05/01/2011,NaN,4.875,114750.79,15,345,343.0,02/2040,17780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
999983,149180644668,06/01/2011,NaN,4.875,114595.67,16,344,342.0,02/2040,17780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
999984,149180644668,07/01/2011,NaN,4.875,114439.91,17,343,341.0,02/2040,17780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
999985,149180644668,08/01/2011,NaN,4.875,114283.52,18,342,340.0,02/2040,17780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
999986,149180644668,09/01/2011,NaN,4.875,114126.50,19,341,339.0,02/2040,17780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
999987,149180644668,10/01/2011,NaN,4.875,113968.84,20,340,338.0,02/2040,17780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
999988,149180644668,11/01/2011,NaN,4.875,113810.54,21,339,337.0,02/2040,17780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
999989,149180644668,12/01/2011,NaN,4.875,113651.60,22,338,336.0,02/2040,17780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
999990,149180644668,01/01/2012,NaN,4.875,113492.01,23,337,335.0,02/2040,17780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
999991,149180644668,02/01/2012,NaN,4.875,113331.77,24,336,334.0,02/2040,17780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
999992,149180644668,03/01/2012,NaN,4.875,113170.88,25,335,333.0,02/2040,17780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
999993,149180644668,04/01/2012,NaN,4.875,113009.34,26,334,332.0,02/2040,17780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
999994,149180644668,05/01/2012,NaN,4.875,112847.14,27,333,331.0,02/2040,17780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
999995,149180644668,06/01/2012,NaN,4.875,112684.28,28,332,330.0,02/2040,17780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
999996,149180644668,07/01/2012,NaN,4.875,112420.76,29,331,328.0,02/2040,17780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
999997,149180644668,08/01/2012,NaN,4.875,112256.19,30,330,327.0,02/2040,17780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
999998,149180644668,09/01/2012,NaN,4.875,112090.93,31,329,326.0,02/2040,17780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
999999,149180644668,10/01/2012,NaN,4.875,111925.00,32,328,325.0,02/2040,17780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N

Displays the test set which is everything not before 2015

In [91]:
test

,loan_id,DATE,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
72,100013622306,01/01/2015,NaN,4.750,64120.85,60,120,119.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
73,100013622306,02/01/2015,NaN,4.750,63697.94,61,119,118.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
74,100013622306,03/01/2015,NaN,4.750,63273.36,62,118,117.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
75,100013622306,04/01/2015,NaN,4.750,62847.10,63,117,116.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
76,100013622306,05/01/2015,NaN,4.750,62419.15,64,116,115.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
77,100013622306,06/01/2015,NaN,4.750,61989.51,65,115,114.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
78,100013622306,07/01/2015,NaN,4.750,61558.17,66,114,113.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
79,100013622306,08/01/2015,NaN,4.750,61125.12,67,113,112.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
80,100013622306,09/01/2015,NaN,4.750,60690.35,68,112,111.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
81,100013622306,10/01/2015,NaN,4.750,60253.86,69,111,110.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
82,100013622306,11/01/2015,NaN,4.750,59815.64,70,110,109.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
83,100013622306,12/01/2015,NaN,4.750,59375.69,71,109,108.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
84,100013622306,01/01/2016,NaN,4.750,58934.00,72,108,107.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
85,100013622306,02/01/2016,NaN,4.750,58490.56,73,107,106.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y
86,100013622306,03/01/2016,NaN,4.750,58045.37,74,106,105.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
87,100013622306,04/01/2016,NaN,4.750,57598.41,75,105,104.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
88,100013622306,05/01/2016,NaN,4.750,57149.68,76,104,103.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
89,100013622306,06/01/2016,NaN,4.750,57149.68,77,103,103.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
90,100013622306,07/01/2016,NaN,4.750,56246.89,78,102,101.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
91,100013622306,08/01/2016,NaN,4.750,55792.81,79,101,100.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
92,100013622306,09/01/2016,NaN,4.750,55336.94,80,100,99.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
93,100013622306,10/01/2016,NaN,4.750,54879.26,81,99,98.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
94,100013622306,11/01/2016,NaN,4.750,54419.77,82,98,97.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
95,100013622306,12/01/2016,NaN,4.750,53958.46,83,97,96.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
96,100013622306,01/01/2017,NaN,4.750,53495.33,84,96,95.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
97,100013622306,02/01/2017,NaN,4.750,53030.36,85,95,94.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
98,100013622306,03/01/2017,NaN,4.750,53030.36,86,94,94.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
99,100013622306,04/01/2017,NaN,4.750,52094.89,87,93,92.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
100,100013622306,05/01/2017,NaN,4.750,51624.38,88,92,91.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
101,100013622306,06/01/2017,NaN,4.750,51152.01,89,91,90.0,01/2025,47300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999837,149175953968,02/01/2017,NaN,4.625,67776.89,83,448,NaN,06/2054,16980,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,N
999838,149175953968,03/01/2017,NaN,4.625,67710.47,84,447,NaN,06/2054,16980,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,N
999839,149175953968,04/01/2017,NaN,4.625,67653.47,85,446,NaN,06/2054,16980,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,N
999840,149175953968,05/01/2017,NaN,4.625,67596.25,86,445,NaN,06/2054,16980,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,N
999841,149175953968,06/01/2017,NaN,4.625,67538.81,87,444,NaN,06/2054,16980,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,N
999842,149175953968,07/01/2017,OTHER,4.625,67481.15,88,443,NaN,06/2054,16980,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,N
999843,149175953968,08/01/2017,NaN,4.625,67423.26,89,442,NaN,06/2054,16980,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,N
999844,149175953968,09/01/2017,NaN,4.625,67365.15,90,441,NaN,06/2054,16980,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,N
999845,149175953968,10/01/2017,NaN,4.625,67306.82,91,440,NaN,06/2054,16980,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,N
999846,149175953968,11/01/2017,NaN,4.625,67248.26,92,439,NaN,06/2054,16980,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,N
999847,149175953968,12/01/2017,NaN,4.625,67189.48,93,438,NaN,06/2054,16980,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,N
999848,149175953968,01/01/2018,NaN,4.625,67130.47,94,437,NaN,06/2054,16980,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,N
999849,149175953968,02/01/2018,NaN,4.625,67071.23,95,436,NaN,06/2054,16980,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,N
999850,149175953968,03/01/2018,NaN,4.625,67011.76,96,435,NaN,06/2054,16980,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,N
999851,149175953968,04/01/2018,NaN,4.625,66952.06,97,434,NaN,06/2054,16980,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,N
999852,149175953968,05/01/2018,NaN,4.625,66892.13,98,433,NaN,06/2054,16980,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,N
999853,149175953968,06/01/2018,NaN,4.625,66831.97,99,432,NaN,06/2054,16980,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,N
999854,149175953968,07/01/2018,NaN,4.625,66771.58,100,431,NaN,06/2054,16980,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,N
999855,149175953968,08/01/2018,NaN,4.625,66710.96,101,430,NaN,06/2054,16980,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,N
999856,149175953968,09/01/2018,NaN,4.625,66650.11,102,429,NaN,06/2054,16980,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,N
999857,149175953968,10/01/2018,NaN,4.625,66589.02,103,428,NaN,06/2054,16980,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,N
999858,149175953968,11/01/2018,NaN,4.625,66527.70,104,427,NaN,06/2054,16980,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,N
999859,149175953968,12/01/2018,NaN,4.625,66466.14,105,426,NaN,06/2054,16980,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,N
999860,149175953968,01/01/2019,NaN,4.625,66404.34,106,425,NaN,06/2054,16980,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,N
999861,149175953968,02/01/2019,NaN,4.625,66342.30,107,424,NaN,06/2054,16980,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,N
999862,149175953968,03/01/2019,NaN,4.625,66280.02,108,423,NaN,06/2054,16980,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,Y
999963,149179972416,01/01/2015,NaN,5.250,130187.98,58,302,299.0,03/2040,40380,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
999964,149179972416,02/01/2015,NaN,5.250,129915.65,59,301,298.0,03/2040,40380,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
999965,149179972416,03/01/2015,NaN,5.250,129642.13,60,300,297.0,03/2040,40380,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
999966,149179972416,04/01/2015,NaN,5.250,129642.13,61,299,0.0,03/2040,40380,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN